In [1]:
import pandas as pd

orders = pd.read_csv("../data/olist_orders_dataset.csv")

order_items = pd.read_csv("../data/olist_order_items_dataset.csv")

reviews = pd.read_csv("../data/olist_order_reviews_dataset.csv")

products = pd.read_csv("../data/olist_products_dataset.csv")

print(orders.shape)
print(order_items.shape)
print(reviews.shape)
print(products.shape)

(99441, 8)
(112650, 7)
(99224, 7)
(32951, 9)

In [2]:
returned_orders = reviews[reviews['review_score'] <= 2]

returned_orders.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
5,15197aa66ff4d0650b5434f1b46cda19,b18dcdf73be66366873cd26c5724d1dc,1,NaN,NaN,2018-04-13 00:00:00,2018-04-16 00:39:37
16,9314d6f9799f5bfba510cc7bcd468c01,0dacf04c5ad59fd5a0cc1faa07c34e39,2,NaN,"GOSTARIA DE SABER O QUE HOUVE, SEMPRE RECEBI E...",2018-01-18 00:00:00,2018-01-20 21:25:45
19,373cbeecea8286a2b66c97b1b157ec46,583174fbe37d3d5f0d6661be3aad1786,1,Não chegou meu produto,Péssimo,2018-08-15 00:00:00,2018-08-15 04:10:37
29,2c5e27fc178bde7ac173c9c62c31b070,0ce9a24111d850192a933fcaab6fbad3,1,NaN,Não gostei ! Comprei gato por lebre,2017-12-13 00:00:00,2017-12-16 07:14:07
32,58044bca115705a48fe0e00a21390c54,68e55ca79d04a79f20d4bfc0146f4b66,1,NaN,Sempre compro pela Internet e a entrega ocorre...,2018-04-08 00:00:00,2018-04-09 12:22:39

In [3]:
print(returned_orders.shape)

(14575, 7)

In [4]:
returns = returned_orders[['order_id']]

returns.head()

                            order_id
5   b18dcdf73be66366873cd26c5724d1dc
16  0dacf04c5ad59fd5a0cc1faa07c34e39
19  583174fbe37d3d5f0d6661be3aad1786
29  0ce9a24111d850192a933fcaab6fbad3
32  68e55ca79d04a79f20d4bfc0146f4b66

In [5]:
merged = returns.merge(
    order_items,
    on='order_id'
)

merged.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,b18dcdf73be66366873cd26c5724d1dc,1,c45d02cc82cd779835094de9b29272cb,da8622b14eb17ae2831f4ac5b9dab84a,2018-04-13 20:10:35,99.90,13.20
1,b18dcdf73be66366873cd26c5724d1dc,2,c45d02cc82cd779835094de9b29272cb,da8622b14eb17ae2831f4ac5b9dab84a,2018-04-13 20:10:35,99.90,13.20
2,b18dcdf73be66366873cd26c5724d1dc,3,4e3550b4ebca5e32ccc3d32b3470e31f,41ab63a91b8b264e8c8780368bf1dd5b,2018-04-23 20:10:35,119.00,4.40
3,b18dcdf73be66366873cd26c5724d1dc,4,c45d02cc82cd779835094de9b29272cb,da8622b14eb17ae2831f4ac5b9dab84a,2018-04-13 20:10:35,99.90,13.20
4,0dacf04c5ad59fd5a0cc1faa07c34e39,1,4413a608a42bd21bbf9d5abbd58c249a,7ddcbb64b5bc1ef36ca8c151f6ec77df,2017-12-26 13:32:58,166.99,21.66

In [6]:
print(merged.shape)

(18109, 7)

In [7]:
merged = merged.merge(
    products,
    on='product_id'
)

merged.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,b18dcdf73be66366873cd26c5724d1dc,1,c45d02cc82cd779835094de9b29272cb,da8622b14eb17ae2831f4ac5b9dab84a,2018-04-13 20:10:35,99.90,13.20,cama_mesa_banho,57.0,246.0,2.0,950.0,46.0,6.0,36.0
1,b18dcdf73be66366873cd26c5724d1dc,2,c45d02cc82cd779835094de9b29272cb,da8622b14eb17ae2831f4ac5b9dab84a,2018-04-13 20:10:35,99.90,13.20,cama_mesa_banho,57.0,246.0,2.0,950.0,46.0,6.0,36.0
2,b18dcdf73be66366873cd26c5724d1dc,3,4e3550b4ebca5e32ccc3d32b3470e31f,41ab63a91b8b264e8c8780368bf1dd5b,2018-04-23 20:10:35,119.00,4.40,cama_mesa_banho,30.0,568.0,1.0,900.0,17.0,22.0,17.0
3,b18dcdf73be66366873cd26c5724d1dc,4,c45d02cc82cd779835094de9b29272cb,da8622b14eb17ae2831f4ac5b9dab84a,2018-04-13 20:10:35,99.90,13.20,cama_mesa_banho,57.0,246.0,2.0,950.0,46.0,6.0,36.0
4,0dacf04c5ad59fd5a0cc1faa07c34e39,1,4413a608a42bd21bbf9d5abbd58c249a,7ddcbb64b5bc1ef36ca8c151f6ec77df,2017-12-26 13:32:58,166.99,21.66,cool_stuff,57.0,1620.0,1.0,2350.0,16.0,40.0,16.0

In [8]:
print(merged.shape)

(18109, 15)

In [9]:
sku_returns = merged.groupby(
    'product_id'
).size().reset_index(
    name='return_count'
)

sku_returns.head()

                         product_id  return_count
0  0009406fd7479715e4bef61dd91f2462             1
1  0011c512eb256aa0dbbb544d8dffcf6e             1
2  001795ec6f1b187d37335e1c4704762e             4
3  001b72dfd63e9833e8c02742adf472e3             4
4  00210e41887c2a8ef9f791ebc780cc36             1

In [10]:
sku_returns = sku_returns.sort_values(
    by='return_count',
    ascending=False
)

sku_returns.head(10)

                            product_id  return_count
2373  422879e10f46682990de24d770e7f83d            95
5336  99a4788cb24856965c36a24e339b6058            80
2965  53759a2ecddad2bb87a079a1f1519f73            77
1933  368c6c730842d78016ad823897a372db            75
6040  aca2eb7d00ea1a7b8ebd4e68314663af            74
2016  389d119b48cf3043d311335e499d9c6b            61
8086  e53e557d5a159f5aa2c5e995dfdf244b            58
6363  b532349fe46b38fbc7bb3914c1bdae07            52
1949  36f60d45225e60c7da4558b070ce4b60            48
4348  7c1bd920dbdf22470b68bde975dd3ccf            45

In [11]:
sku_returns.to_csv(
    "../reports/sku_return_rates.csv",
    index=False
)

print("Report saved successfully")

Report saved successfully